// Generated by grunt: browserify-imports
(function moduleInit_startComponents() {

	// Add require for other modules here
	// require('my.module.core');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./ui-progress');
	var angularModuleDependencies = ["start.components.uiProgress"];
	// EndRequire

	// Add your angular module dependencies here
	// angularModuleDependencies.push('other.module');

	try {
		console.log('loading module start.components');
		angular.module('start.components', angularModuleDependencies);
	} catch (e) {
		console.log('start.components is already defined.');}
	}
)();
