// Generated by grunt: browserify-imports
(function moduleInit_guiComponents() {

	// Add require for other modules here
	// require('../../libs/grunt-icons-loader.js');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	var angularModuleDependencies = [];
	// EndRequire

	// Add your angular module dependencies here
	// angularModuleDependencies.push('other.module');

	try {
		console.log('loading module gui.components');
		angular.module('gui.blend', angularModuleDependencies);
	} catch (e) {
		console.log('gui.components is already defined.');}
	}
)();
