// Generated by grunt: browserify-imports
(function moduleInit_yodaCatwalk() {

	// require('../yoda.helpers.filters');
	// require('ace-editor-builds');
	require('angular-ui-ace');

	// Add require for other modules here
	require('../yoda.catwalk.components');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./component-page');
	require('./layout');
	require('./menu');
	var angularModuleDependencies = ["yoda.catwalk.componentPage","yoda.catwalk.layout","yoda.catwalk.menu"];
	// EndRequire

	// Add your angular module dependencies here
	angularModuleDependencies.push('ui.ace');
	angularModuleDependencies.push('yoda.catwalk.components');

	try {
		console.log('loading module yoda.catwalk');
		angular.module('yoda.catwalk', angularModuleDependencies);
	} catch (e) {
		console.log('yoda.catwalk is already defined.');}
	}
)();
