// Generated by grunt: browserify-imports
(function moduleInit_yodaHelpersFilters() {

	// Add require for other modules here
	// require('my.module.core');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./trust-html');
	var angularModuleDependencies = ["yoda.helpers.filters.trustHtml"];
	// EndRequire

	// Add your angular module dependencies here
	// angularModuleDependencies.push('other.module');

	try {
		console.log('loading module yoda.helpers.filters');
		angular.module('yoda.helpers.filters', angularModuleDependencies);
	} catch (e) {
		console.log('yoda.helpers.filters is already defined.');}
	}
)();
