// Generated by grunt: browserify-imports
(function moduleInit_startFormsComponents() {

	// Add require for other modules here

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./email-input');
	require('./text-input');
	var angularModuleDependencies = ["start.forms.components.emailInput","start.forms.components.textInput"];
	// EndRequire

	// Add your angular module dependencies here
	// angularModuleDependencies.push('other.module');

	try {
		console.log('loading module start.forms.components');
		angular.module('start.forms.components', angularModuleDependencies);
	} catch (e) {
		console.log('start.forms.components is already defined.');}
	}
)();
