// Generated by grunt: browserify-imports
(function moduleInit_yodaCatwalkComponents() {
	// Add require for other modules here
	// require('my.module.core');
	require('../yoda.helpers.filters');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./_fab-material');
	require('./_hamburger-menu-icon');
	require('./_page-header');
	require('./collapse');
	require('./component-code-editor');
	require('./component-params-table');
	require('./component-playground');
	require('./fab-menu');
	require('./lightsabers-menu-icon');
	var angularModuleDependencies = ["yoda.catwalk.components.collapse","yoda.catwalk.components.componentCodeEditor","yoda.catwalk.components.componentParamsTable","yoda.catwalk.components.componentPlayground","yoda.catwalk.components.fabMenu","yoda.catwalk.components.lightsabersMenuIcon"];
	// EndRequire

	// Add your angular module dependencies here
	angularModuleDependencies.push('yoda.helpers.filters');

	try {
		console.log('loading module yoda.catwalk.components');
		angular.module('yoda.catwalk.components', angularModuleDependencies);
	} catch (e) {
		console.log('yoda.catwalk.components is already defined.');}
	}
)();
