// Generated by grunt: browserify-imports
(function moduleInit_guiNgComponents() {

	// Add require for other modules here
	// require('my.module.core');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./alert');
	require('./grunticon-embed');
	var angularModuleDependencies = ["gui.ng.components.alert","gui.ng.components.grunticonEmbed"];
	// EndRequire

	// Add your angular module dependencies here
	// angularModuleDependencies.push('other.module');

	try {
		console.log('loading module gui.ng.components');
		angular.module('gui.ng.components', angularModuleDependencies);
	} catch (e) {
		console.log('gui.ng.components is already defined.');}
	}
)();
