// Generated by grunt: browserify-imports
(function moduleInit_startFormsFieldsets() {

	// Add require for other modules here
	require('angular-messages');
	require('../start.forms.components');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./input-row');
	var angularModuleDependencies = ["start.forms.fieldsets.inputRow"];
	// EndRequire

	// Add your angular module dependencies here
	angularModuleDependencies.push('ngMessages');
	angularModuleDependencies.push('start.forms.components');

	try {
		console.log('loading module start.forms.fieldsets');
		angular.module('start.forms.fieldsets', angularModuleDependencies);
	} catch (e) {
		console.log('start.forms.fieldsets is already defined.');}
	}
)();
